// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRXr5aYRjO1nF3aqGZ2PVkh4i0TntCOPg',
    appId: '1:174431162482:web:410ab61092982f5d1632eb',
    messagingSenderId: '174431162482',
    projectId: 'rental-shit',
    authDomain: 'rental-shit.firebaseapp.com',
    storageBucket: 'rental-shit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_XAnAgEGXWohIhfYDOLxXAEwnpLp_oR0',
    appId: '1:174431162482:android:95b8e58aa454aa271632eb',
    messagingSenderId: '174431162482',
    projectId: 'rental-shit',
    storageBucket: 'rental-shit.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRXr5aYRjO1nF3aqGZ2PVkh4i0TntCOPg',
    appId: '1:174431162482:web:410ab61092982f5d1632eb',
    messagingSenderId: '174431162482',
    projectId: 'rental-shit',
    authDomain: 'rental-shit.firebaseapp.com',
    storageBucket: 'rental-shit.firebasestorage.app',
  );
}
