// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRNzvDYT93kUV4ZXt17IScr7U588XnAg',
    appId: '1:851364392108:web:bc486d0722fc682b70c309',
    messagingSenderId: '851364392108',
    projectId: 'rentalcrates-ad96e',
    authDomain: 'rentalcrates-ad96e.firebaseapp.com',
    storageBucket: 'rentalcrates-ad96e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBINenZlSMn0d26F6ayEsiaOk4dte11IVE',
    appId: '1:851364392108:android:5c1255cf325747bb70c309',
    messagingSenderId: '851364392108',
    projectId: 'rentalcrates-ad96e',
    storageBucket: 'rentalcrates-ad96e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5ih307kAWup6ame-RDRGHRO2M7JaSlM',
    appId: '1:851364392108:ios:75beaf61b2a24ac670c309',
    messagingSenderId: '851364392108',
    projectId: 'rentalcrates-ad96e',
    storageBucket: 'rentalcrates-ad96e.firebasestorage.app',
    iosBundleId: 'com.example.rentalCrates1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5ih307kAWup6ame-RDRGHRO2M7JaSlM',
    appId: '1:851364392108:ios:75beaf61b2a24ac670c309',
    messagingSenderId: '851364392108',
    projectId: 'rentalcrates-ad96e',
    storageBucket: 'rentalcrates-ad96e.firebasestorage.app',
    iosBundleId: 'com.example.rentalCrates1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChRNzvDYT93kUV4ZXt17IScr7U588XnAg',
    appId: '1:851364392108:web:74ec343070da5b0570c309',
    messagingSenderId: '851364392108',
    projectId: 'rentalcrates-ad96e',
    authDomain: 'rentalcrates-ad96e.firebaseapp.com',
    storageBucket: 'rentalcrates-ad96e.firebasestorage.app',
  );
}
